containers:
  skiff_core:
    image: skiff/core:latest
    mounts:
    - /lib/modules:/lib/modules
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    - /dev:/dev
    - /mnt:/mnt
    privileged: true
    capAdd:
    - ALL
    hostIPC: true
    hostPID: true
    hostUTS: true
    hostNetwork: true
    securityOpt:
    - seccomp=unconfined
    tmpFs:
      /run: rw,noexec,nosuid,size=65536k
users:
  core:
    auth:
      container: skiff_core
      copyRootKeys: true
images:
  skiff/core:latest:
    build:
      source: /home/paralin/Documents/minimal_docker/coreenv
